model_hps:
  hidden_dim: 64

train_hps:
  num_timesteps_per_rollout: 4800
  max_timesteps_per_episode: 1600
  total_timesteps: 1000000
  num_epochs_per_rollout: 5
  minibatch_size: 960
  gamma: 0.95
  lam: 0.99
  eps: 0.2
  alpha: 0.1
  actor_lr: 2e-4
  critic_lr: 2e-4
  actor_betas: [0.9, 0.999]
  critic_betas: [0.9, 0.999]
  max_grad_norm: 0.5
  checkpoint_path: "checkpoints"
  checkpoint_interval: 96000
